/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as RejectInvitationInvitationIdIndexImport } from './routes/reject-invitation/$invitationId/index'
import { Route as AcceptInvitationInvitationIdIndexImport } from './routes/accept-invitation/$invitationId/index'
import { Route as AuthenticatedTeamsIndexImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedTeamsEditMemberImport } from './routes/_authenticated/teams/edit-member'
import { Route as AuthenticatedTeamsTeamIdIndexImport } from './routes/_authenticated/teams/$teamId/index'
import { Route as AuthenticatedTeamsTeamIdAddMemberImport } from './routes/_authenticated/teams/$teamId/add-member'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const RejectInvitationInvitationIdIndexRoute =
  RejectInvitationInvitationIdIndexImport.update({
    id: '/reject-invitation/$invitationId/',
    path: '/reject-invitation/$invitationId/',
    getParentRoute: () => rootRoute,
  } as any)

const AcceptInvitationInvitationIdIndexRoute =
  AcceptInvitationInvitationIdIndexImport.update({
    id: '/accept-invitation/$invitationId/',
    path: '/accept-invitation/$invitationId/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTeamsEditMemberRoute =
  AuthenticatedTeamsEditMemberImport.update({
    id: '/teams/edit-member',
    path: '/teams/edit-member',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTeamsTeamIdIndexRoute =
  AuthenticatedTeamsTeamIdIndexImport.update({
    id: '/teams/$teamId/',
    path: '/teams/$teamId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTeamsTeamIdAddMemberRoute =
  AuthenticatedTeamsTeamIdAddMemberImport.update({
    id: '/teams/$teamId/add-member',
    path: '/teams/$teamId/add-member',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/teams/edit-member': {
      id: '/_authenticated/teams/edit-member'
      path: '/teams/edit-member'
      fullPath: '/teams/edit-member'
      preLoaderRoute: typeof AuthenticatedTeamsEditMemberImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/accept-invitation/$invitationId/': {
      id: '/accept-invitation/$invitationId/'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/reject-invitation/$invitationId/': {
      id: '/reject-invitation/$invitationId/'
      path: '/reject-invitation/$invitationId'
      fullPath: '/reject-invitation/$invitationId'
      preLoaderRoute: typeof RejectInvitationInvitationIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/teams/$teamId/add-member': {
      id: '/_authenticated/teams/$teamId/add-member'
      path: '/teams/$teamId/add-member'
      fullPath: '/teams/$teamId/add-member'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdAddMemberImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/teams/$teamId/': {
      id: '/_authenticated/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedTeamsEditMemberRoute: typeof AuthenticatedTeamsEditMemberRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedTeamsTeamIdAddMemberRoute: typeof AuthenticatedTeamsTeamIdAddMemberRoute
  AuthenticatedTeamsTeamIdIndexRoute: typeof AuthenticatedTeamsTeamIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTeamsEditMemberRoute: AuthenticatedTeamsEditMemberRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedTeamsTeamIdAddMemberRoute:
    AuthenticatedTeamsTeamIdAddMemberRoute,
  AuthenticatedTeamsTeamIdIndexRoute: AuthenticatedTeamsTeamIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/teams/edit-member': typeof AuthenticatedTeamsEditMemberRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdIndexRoute
  '/reject-invitation/$invitationId': typeof RejectInvitationInvitationIdIndexRoute
  '/teams/$teamId/add-member': typeof AuthenticatedTeamsTeamIdAddMemberRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/teams/edit-member': typeof AuthenticatedTeamsEditMemberRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdIndexRoute
  '/reject-invitation/$invitationId': typeof RejectInvitationInvitationIdIndexRoute
  '/teams/$teamId/add-member': typeof AuthenticatedTeamsTeamIdAddMemberRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/teams/edit-member': typeof AuthenticatedTeamsEditMemberRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/accept-invitation/$invitationId/': typeof AcceptInvitationInvitationIdIndexRoute
  '/reject-invitation/$invitationId/': typeof RejectInvitationInvitationIdIndexRoute
  '/_authenticated/teams/$teamId/add-member': typeof AuthenticatedTeamsTeamIdAddMemberRoute
  '/_authenticated/teams/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/login'
    | '/teams/edit-member'
    | '/teams'
    | '/accept-invitation/$invitationId'
    | '/reject-invitation/$invitationId'
    | '/teams/$teamId/add-member'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/login'
    | '/teams/edit-member'
    | '/teams'
    | '/accept-invitation/$invitationId'
    | '/reject-invitation/$invitationId'
    | '/teams/$teamId/add-member'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/teams/edit-member'
    | '/_authenticated/teams/'
    | '/accept-invitation/$invitationId/'
    | '/reject-invitation/$invitationId/'
    | '/_authenticated/teams/$teamId/add-member'
    | '/_authenticated/teams/$teamId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AcceptInvitationInvitationIdIndexRoute: typeof AcceptInvitationInvitationIdIndexRoute
  RejectInvitationInvitationIdIndexRoute: typeof RejectInvitationInvitationIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AcceptInvitationInvitationIdIndexRoute:
    AcceptInvitationInvitationIdIndexRoute,
  RejectInvitationInvitationIdIndexRoute:
    RejectInvitationInvitationIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth/login",
        "/accept-invitation/$invitationId/",
        "/reject-invitation/$invitationId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/teams/edit-member",
        "/_authenticated/teams/",
        "/_authenticated/teams/$teamId/add-member",
        "/_authenticated/teams/$teamId/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/_authenticated/teams/edit-member": {
      "filePath": "_authenticated/teams/edit-member.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/teams/": {
      "filePath": "_authenticated/teams/index.tsx",
      "parent": "/_authenticated"
    },
    "/accept-invitation/$invitationId/": {
      "filePath": "accept-invitation/$invitationId/index.tsx"
    },
    "/reject-invitation/$invitationId/": {
      "filePath": "reject-invitation/$invitationId/index.tsx"
    },
    "/_authenticated/teams/$teamId/add-member": {
      "filePath": "_authenticated/teams/$teamId/add-member.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/teams/$teamId/": {
      "filePath": "_authenticated/teams/$teamId/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
