
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: team-manager-api
        command: sleep infinity
        volumes:
            - .:/app

        ports:
            - "8000:8000"
        env_file:
            - .env.dev
