
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: team-manager-api
        command: sleep infinity
        volumes:
            - .:/app

        ports:
            - "8000:8000"
        env_file:
            - .env.dev
        depends_on:
            - db
    db:
        image: postgres:16-alpine
        container_name: team-manager-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env.dev
        ports:
            - "5432:5432"

volumes:
    postgres_data: